### ISSUE TITLE
Module demands login

### ISSUE THREAD

**Issue by emario64** [marcanuy/Joomla-Most-Popular#10]
Hello!
I am using joomla 3.4.1. Slovenian language and I love the idea beehind that module. But.. When I install it and do all about enabling plugin and configuring module all looks good. And cliks are producing some new links in module, but when I try to click on the link in that module, all links are the same <site url>/home/login  Even if I am logged in as registered user or even Super user it is the same. Am i missing something or there is some issue about that?

Mario E.

**Comment by marcanuy** [comment]
Hi, this module was meant for J!3.1, it is not maintained anymore.
