### ISSUE TITLE
Content not showing

### ISSUE THREAD

**Issue by foxvor** [marcanuy/Joomla-Most-Popular#4]
Hello, I installed the extention, activated the plugin and configured the module and I don't get any article showing on the position. I get the title and the space, but no article is being shown. I have even try configuring the module with "All categories" and "All time" and still no article is shown. 

What am I missing, can you help me? Thanks

Joomla 3.x on Vocal template: http://beta.transportesk.com/

Section: Próximos Eventos

**Comment by jcsfull** [comment]
Me pasa lo mismo que foxvor (Hello, I installed the extention, activated the plugin and configured the module and I don't get any article showing on the position. I get the title and the space, but no article is being shown.) Joomla 3.4.1 Template yoo_master2 (warp 7)

**Comment by mohammadrezas** [comment]
I TOO .

**Comment by marcanuy** [comment]
Sorry, this repository is not maintained anymore, I keep the source code published for the community to improve it.
