### ISSUE TITLE
Most popular among featured

### ISSUE THREAD

**Issue by Airfan** [marcanuy/Joomla-Most-Popular#7]
// Filter by featured state
    $featured = $params->get('show_front', 1) == 1 ? 'show' : 'hide';
    switch ($featured)
      {
      case 'hide':
	$query->where('a.featured = 0');
	break;

      case 'only':
	$query->where('a.featured = 1');
	break;

      case 'show':
      default:
	// Normally we do not discriminate
	// between featured/unfeatured items.
	break;
      }

The only possible values for $featured are "show" and "hide". "Only" is not reachable. Is that future feature? 
So at the moment you can:
1. Get top content among non featured articles.
2. Get top content among all articles.

**Comment by marcanuy** [comment]
Sorry, this repository is not maintained anymore, I keep the source code published for the community to improve it.
